version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:8080"
    links:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./docker/bd:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pokegame
    ports:
      - 3300:3306
